run-name: Linting, testing, and building 🔎
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm ci
      - name: Building the app
        run: npm run build:prod
      - name: Linting typescript with ESLint
        run: npm run lint:ts
      - name: Linting scss with Stylelint
        run: npm run lint:scss
      - name: Unit testing with Jest
        run: npm run test:unit
      - name: Building storybook
        run: npm run storybook:build
      - name: Screenshot testing with Loki
        run: npm run test:ui:ci
